DECLARE
  V_COUNTRYID LOCATIONS.COUNTRY_ID%TYPE:='CA';
  V_LOC_ID LOCATIONS.LOCATION_ID%TYPE;
  V_COUNTER NUMBER(2):=1;
  V_NEW_CITY LOCATIONS.CITY%TYPE:='MONTREAL';
BEGIN
  SELECT MAX(LOCATION_ID) INTO V_LOC_ID FROM LOCATIONS
  WHERE COUNTRY_ID = V_COUNTRYID;
  LOOP
    INSERT INTO LOCATIONS(LOCATION_ID, CITY, COUNTRY_ID)
    VALUES ((V_LOC_ID + V_COUNTER), V_NEW_CITY, V_COUNTRYID);
    V_COUNTER := V_COUNTER+1;
    EXIT WHEN V_COUNTER > 3;
  END LOOP;
END;