SET SERVEROUTPUT ON
DECLARE
  CURSOR C_EMP_CURSOR IS
    SELECT EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES
    WHERE DEPARTMENT_ID = 30;
BEGIN
  FOR EMP_RECORD IN C_EMP_CURSOR
  LOOP
    DBMS_OUTPUT.PUT_LINE(EMP_RECORD.EMPLOYEE_ID||' '
                              ||EMP_RECORD.LAST_NAME);
  END LOOP;
END;