DECLARE
  V_TOTAL INTEGER:=0;
BEGIN
  FOR I IN 1..10 LOOP
    V_TOTAL := V_TOTAL + I;
    DBMS_OUTPUT.PUT_LINE('TOTAL IS: '||V_TOTAL||' CONTEO '||I);--25
    CONTINUE WHEN I > 5;
    V_TOTAL :=  V_TOTAL + I;
    DBMS_OUTPUT.PUT_LINE('OUT OF LOOP TOTAL IS: '||V_TOTAL);--30
  END LOOP;
END;