DECLARE
  V_TOTAL NUMBER:=0;
BEGIN
  <<BEFORETOPLOOP>>
  FOR I IN 1..10 LOOP
    V_TOTAL := V_TOTAL+1;--3
    DBMS_OUTPUT.PUT_LINE('TOTAL IS: '||V_TOTAL||' CONTEO '||I);
    FOR J IN 1..10 LOOP
      CONTINUE BEFORETOPLOOP WHEN I + J  > 5;
      V_TOTAL := V_TOTAL+1;
    END LOOP;
  END LOOP;
END;