DECLARE
  V_DATE_OF_JOINING DATE;
BEGIN
  --V_DATE_OF_JOINING := '02-FEB-2000'; --CONVERSIÓN IMPLÍCITA
  --V_DATE_OF_JOINING := 'FEBRUARY 02, 2000'; --ERROR EN LA CONVERSIÓN DE TIPOS DE DATOS
  V_DATE_OF_JOINING := TO_DATE('02 02,2000','MM DD,YYYY');--CONVERSIÓN EXPLÍCITA
  
  DBMS_OUTPUT.put_line(TO_CHAR(V_DATE_OF_JOINING,'MONTHDD, YYYY'));--CONVERSIÓN EXPLÍCITA
  DBMS_OUTPUT.PUT_LINE(TO_CHAR(SYSDATE,'MONTH/DD/YYYY'));--CONVERSIÓN EXPLÍCITA
END;