SET SERVEROUTPUT ON

DECLARE
  V_SALARY NUMBER(6):=6000;
  V_SAL_HIKE VARCHAR2(5):='1000';
  V_TOTAL_SALARY V_SALARY%TYPE;
BEGIN
  V_TOTAL_SALARY:=V_SALARY+V_SAL_HIKE; --AQUÍ IMPLICITAMENTE PASÓ DE VARCHAR A NUMBER
  DBMS_OUTPUT.put_line(V_TOTAL_SALARY);
END;

/*
LAS CONVERSIONES IMPLÍCITAS SE PRODUCEN ENTRE LO SIGUIENTE:
  -CARACTERES Y NÚMEROS
  -CARACTERES Y FECHAS
*/
