SET SERVEROUTPUT ON
DECLARE
  V_DEPTNO NUMBER:=80;
  CURSOR C_EMP_CURSOR IS
    SELECT LAST_NAME, SALARY, MANAGER_ID 
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = V_DEPTNO;
BEGIN
  FOR C_EMP_REG IN C_EMP_CURSOR 
  LOOP
    IF C_EMP_REG.SALARY < 5000 AND (C_EMP_REG.MANAGER_ID = 101 OR C_EMP_REG.MANAGER_ID = 124) THEN
      DBMS_OUTPUT.PUT_LINE(C_EMP_REG.LAST_NAME||' DUE FOR A RAISE');
      ELSE
        DBMS_OUTPUT.PUT_LINE(C_EMP_REG.LAST_NAME||' NOT DUE FOR A RAISE');
    END IF;
  END LOOP;
END;