SET SERVEROUTPUT ON
DECLARE
  CURSOR C_EMP_CURSOR IS 
  SELECT EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES
  WHERE DEPARTMENT_ID = 30;
  
  V_EMPNO EMPLOYEES.EMPLOYEE_ID%TYPE;
  V_LNAME EMPLOYEES.LAST_NAME%TYPE;
BEGIN
  OPEN C_EMP_CURSOR;
  FETCH C_EMP_CURSOR INTO V_EMPNO, V_LNAME;
  DBMS_OUTPUT.PUT_LINE(V_EMPNO||' '||V_LNAME);  
END;