--EN ESTE CURSOR QUE ES EL MISMO QUE EL PRIMERO SÍ SE TRAEN TODOS LOS REGISTROS
SET SERVEROUTPUT ON
DECLARE
  CURSOR C_EMP_CURSOR IS 
  SELECT EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES
  WHERE DEPARTMENT_ID = 30;
  
  V_EMPNO EMPLOYEES.EMPLOYEE_ID%TYPE;
  V_LNAME EMPLOYEES.LAST_NAME%TYPE;
BEGIN
  OPEN C_EMP_CURSOR;
    LOOP
      FETCH C_EMP_CURSOR INTO V_EMPNO, V_LNAME;
      EXIT WHEN C_EMP_CURSOR%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE(V_EMPNO||' '||V_LNAME);
    END LOOP;
  CLOSE C_EMP_CURSOR;
 
END;