DECLARE
  CURSOR C_EMP_CURSOR IS
  SELECT EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES
  WHERE DEPARTMENT_ID = 30;
  
  V_EMP_RECORD C_EMP_CURSOR%ROWTYPE;
BEGIN
  OPEN C_EMP_CURSOR;
    LOOP
      FETCH C_EMP_CURSOR INTO V_EMP_RECORD;
      EXIT WHEN C_EMP_CURSOR%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE(V_EMP_RECORD.EMPLOYEE_ID||' '||
                          V_EMP_RECORD.LAST_NAME);
    END LOOP;
  CLOSE C_EMP_CURSOR;
END;