DECLARE
  CURSOR C_EMP(IDENT NUMBER) IS
    SELECT FIRST_NAME, LAST_NAME  FROM EMPLOYEES WHERE DEPARTMENT_ID =IDENT;
BEGIN
  FOR EMP_REG IN C_EMP(30)LOOP
      DBMS_OUTPUT.PUT_LINE(EMP_REG.FIRST_NAME||' '||EMP_REG.LAST_NAME);
    END LOOP;
END;
    