SET SERVEROUTPUT ON
DECLARE
  V_NUM NUMBER:=0;
  V_SAL EMPLOYEES.SALARY%TYPE;
  
  CURSOR C_EMP_CURSOR IS 
    SELECT DISTINCT(SALARY) 
    FROM EMPLOYEES
    ORDER BY SALARY DESC;
  
BEGIN
  OPEN C_EMP_CURSOR;
    FETCH C_EMP_CURSOR INTO V_SAL;
    dbms_output.put_line('Registros insertados primer fetch : '||C_EMP_CURSOR%ROWCOUNT);
    WHILE C_EMP_CURSOR%ROWCOUNT <= V_NUM AND C_EMP_CURSOR%FOUND
  LOOP
    INSERT INTO TOP_SALARIES (SALARY) VALUES(V_SAL);
      FETCH C_EMP_CURSOR INTO V_SAL;
      dbms_output.put_line('Registros insertados segundo fetch: '||C_EMP_CURSOR%ROWCOUNT);
  END LOOP;
  CLOSE C_EMP_CURSOR;
END;