DECLARE
  V_DEPTNO NUMBER:=500;
  V_NAME   VARCHAR2(20):='Testing';
  E_INVALID_DEPARTMENT EXCEPTION;
BEGIN
  UPDATE DEPARTMENTS
  SET DEPARTMENT_NAME = V_NAME
  WHERE DEPARTMENT_ID = V_DEPTNO;
    IF SQL%NOTFOUND THEN
      RAISE E_INVALID_DEPARTMENT;
    END IF;
    COMMIT;
EXCEPTION
  WHEN E_INVALID_DEPARTMENT THEN
    DBMS_OUTPUT.PUT_LINE('EL NÚMERO DE DEPARTAMENTO NO SE ENCUENTRA!!');
END;