DECLARE
V_ENAME EMPLOYEES.LAST_NAME%TYPE;
V_EMP_SAL EMPLOYEES.SALARY%TYPE:=1;
BEGIN
  SELECT LAST_NAME INTO V_ENAME FROM EMPLOYEES
  WHERE SALARY = V_EMP_SAL;
  INSERT INTO MESSAGES(RESULTS)VALUES(V_ENAME ||' - '||V_EMP_SAL);
EXCEPTION
  WHEN NO_DATA_FOUND THEN
  INSERT INTO MESSAGES(RESULTS)VALUES('NO SE ENCONTRARON DATOS PARA EL SALARIO $'||V_EMP_SAL);
  
  WHEN TOO_MANY_ROWS THEN
  INSERT INTO MESSAGES(RESULTS)VALUES('MÁS DE UN EMPLEADO TIENE EL SALARIO DE $6000');
  
  WHEN OTHERS THEN
  INSERT INTO MESSAGES(RESULTS)VALUES('ERROR DESCONOCIDO');
 
  
END;