DECLARE
  CURSOR C_PAISES IS
  SELECT COUNTRY_ID, COUNTRY_NAME FROM COUNTRIES;
  
  V_PAISES C_PAISES%ROWTYPE;
  
BEGIN
  OPEN C_PAISES;
  DBMS_OUTPUT.PUT_LINE('ID '||'PAÍS');
  LOOP
    FETCH C_PAISES INTO V_PAISES;
     EXIT WHEN C_PAISES%ROWCOUNT > 5 OR C_PAISES%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE(V_PAISES.COUNTRY_ID||' '||V_PAISES.COUNTRY_NAME);
   
  END LOOP;
  CLOSE C_PAISES;
  
END;