set serveroutput on
DECLARE
  V_APELLIDO VARCHAR2(30);
  V_NOMBRE EMPLOYEES.FIRST_NAME%TYPE:='JOHN EL PODEROSO';
BEGIN
  SELECT LAST_NAME INTO V_APELLIDO FROM EMPLOYEES
  WHERE FIRST_NAME = V_NOMBRE;
  DBMS_OUTPUT.PUT_LINE('EL APELLIDO DE JOHN ES: '||V_APELLIDO);
EXCEPTION
  WHEN TOO_MANY_ROWS THEN 
    DBMS_OUTPUT.PUT_LINE('
    LA CONSULTA SOLICITADA CONTIENE MÁS DE UN REGISTRO, 
    SE RECOMIENDA QUE UTILICE UN CURSOR PARA QUE DEVUELVA 
    TODOS LOS REGISTROS QUE NECESITA');
    
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('
    LA CONSULTA NO ENCUENTRA NINGÚN RESULTADO PARA EL CRITERIO DE BÚSQUEDA : '||V_NOMBRE);
END;