DECLARE
  V_EVENT VARCHAR2(15);
  V_EVENT2 VARCHAR2(15);
  V_EVENT3 VARCHAR2(15);
  
BEGIN
  V_EVENT:= q'[father's day]';
  V_EVENT2:= q'!father's day!';
  V_EVENT3:= 'father''s day';
  DBMS_OUTPUT.PUT_LINE('EL 3ER DOMINGO DE XUNIO ES: '||V_EVENT);
  DBMS_OUTPUT.PUT_LINE('EL 3ER DOMINGO DE XUNIO ES: '||V_EVENT2);
  DBMS_OUTPUT.PUT_LINE('EL 3ER DOMINGO DE XUNIO ES: '||V_EVENT3);
END;