DECLARE
  EDAD NUMBER:=50;
BEGIN
  IF EDAD < 11 THEN 
      DBMS_OUTPUT.PUT_LINE('SOY UN NIÑO');
    ELSIF EDAD < 20 THEN
      DBMS_OUTPUT.PUT_LINE('SOY UN JÓVEN');
    ELSIF EDAD < 30 THEN
      DBMS_OUTPUT.PUT_LINE('ESTOY EN MIS VEINTES');
    ELSIF EDAD < 40 THEN
      DBMS_OUTPUT.PUT_LINE('ESTOY EN MIS TREINTAS');
    ELSE
      DBMS_OUTPUT.PUT_LINE('SIEMPRE SERÉ JOVEN');
  END IF;
          
END;
