SET SERVEROUTPUT ON
DECLARE
  TYPE DEPT_TABLE_TYPE IS TABLE OF
        DEPARTMENTS%ROWTYPE INDEX BY PLS_INTEGER;
  DEPT_TABLE DEPT_TABLE_TYPE;
  --CADA ELEMENTO DE DEPT_TABLE ES UN REGISTRO
BEGIN
  SELECT * INTO DEPT_TABLE(1) FROM DEPARTMENTS
    WHERE DEPARTMENT_ID=10;
    DBMS_OUTPUT.PUT_LINE(DEPT_TABLE(1).DEPARTMENT_ID ||' '|| DEPT_TABLE(1).DEPARTMENT_NAME||' '||DEPT_TABLE(1).MANAGER_ID);
END;