DECLARE
  TYPE EMPL_TABLE_TYPE IS TABLE OF
    EMPLOYEES%ROWTYPE INDEX BY PLS_INTEGER;
  MY_EMPL_TABLE EMPL_TABLE_TYPE;
  MAX_COUNT NUMBER(3):=104;
BEGIN
  FOR I IN 100..MAX_COUNT LOOP
    SELECT * INTO MY_EMPL_TABLE(I) FROM EMPLOYEES
    WHERE EMPLOYEE_ID = I;
  END LOOP;
  FOR I IN MY_EMPL_TABLE.FIRST..MY_EMPL_TABLE.LAST LOOP
    DBMS_OUTPUT.PUT_LINE(MY_EMPL_TABLE(I).LAST_NAME);
  END LOOP;
END;

