DECLARE
  V_MAX_DEPTNO NUMBER;
  V_DEPT_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN
  SELECT MAX(DEPARTMENT_ID)INTO V_MAX_DEPTNO FROM DEPARTMENTS;
  DBMS_OUTPUT.PUT_LINE('EL MÁXIMO DEPARTAMENTO DE LA TABLA DEPARTMENTS ES: '||V_MAX_DEPTNO);
END;