SET SERVEROUTPUT ON
DECLARE
 HOY DATE:=SYSDATE;
 MANANA HOY%TYPE;
BEGIN
  MANANA:=HOY+1;
  DBMS_OUTPUT.PUT_LINE('HOLA ESTAS SON LAS FECHAS');
  DBMS_OUTPUT.PUT_LINE('HOY ES: '||HOY);
  DBMS_OUTPUT.PUT_LINE('MAÑANA ES: '||MANANA);
END;