/*CREATE TABLE EMP AS SELECT * FROM EMPLOYEES;*/

DECLARE
  V_EMPNO EMP.EMPLOYEE_ID%TYPE:=176;
  V_ASTERISK EMP.STARS%TYPE:=NULL;
  V_SAL EMP.SALARY%TYPE;
BEGIN
  SELECT NVL(ROUND(SALARY/1000),0) INTO V_SAL
  FROM EMP WHERE EMPLOYEE_ID = V_EMPNO;
  
  FOR I IN 1..V_SAL LOOP
    V_ASTERISK := V_ASTERISK||'*';
    END LOOP;
    
  UPDATE EMP SET STARS = V_ASTERISK
  WHERE EMPLOYEE_ID = V_EMPNO;
  COMMIT;
END;
  
