BEGIN
  DBMS_OUTPUT.PUT_LINE('REVISANDO PROMEDIO PARA EMPLEADO CON ID 205');
   IF (CHECK_SAL_PARAMETRO(205) IS NULL) THEN
    DBMS_OUTPUT.PUT_LINE('NO HAY DATOS PARA VALIDAR EMPLEADO CON ID 205');
   ELSIF (CHECK_SAL_PARAMETRO(205)) THEN
    DBMS_OUTPUT.PUT_LINE('EL SALARIO ES MAYOR QUE EL PROMEDIO SALARY > AVERAGE');
    ELSE
    DBMS_OUTPUT.PUT_LINE('EL SALARIO ES MENOR QUE EL PROMEDIO SALARY < AVERAGE');
   END IF;
  DBMS_OUTPUT.PUT_LINE('REVISANDO PROMEDIO PARA EMPLEADO CON ID 70');
   IF (CHECK_SAL_PARAMETRO(70) IS NULL) THEN
    DBMS_OUTPUT.PUT_LINE('NO EXISTEN DATOS PARA VALIDAR EMPLEADO CON ID 70');
   ELSIF (CHECK_SAL_PARAMETRO(70)) THEN
    DBMS_OUTPUT.PUT_LINE('EL SALARIO ES MAYOR QUE EL PROMEDIO');
    ELSE
    DBMS_OUTPUT.PUT_LINE('EL SALARIO ES MENOR QUE EL PROMEDIO');
  END IF;
END;