/*
EN ESTA PRÁCTICA SE ESCRIBIRÁ UN BLOQUE PL/SQL
QUE DECLARE UNA EXCEPCIÓN PARA EL ERROR DE ORACLE
SERVER ORA-02292 (INTEGRITY CONSTRAINT VIOLATED - CHILD RECORD FOUND).
EL BLOQUE COMPROBARÁ LA EXCEPCIÓN Y MOSTRARÁ EL MENSAJE DE ERROR
*/

DECLARE
  E_CHILDREN_RECORD_EXISTS EXCEPTION;
  PRAGMA EXCEPTION_INIT(E_CHILDREN_RECORD_EXISTS, -02292);
BEGIN
  DBMS_OUTPUT.PUT_LINE('BORRANDO DEPARTAMENTO 40 ...............');
  DELETE FROM DEPARTMENTS WHERE DEPARTMENT_ID = 40;
EXCEPTION
  WHEN E_CHILDREN_RECORD_EXISTS THEN
    DBMS_OUTPUT.PUT_LINE('ESTE REGISTRO NO SE PUEDE BORRAR YA QUE EXISTEN EMPLEADOS EN ESTE DEPARTAMENTO');
  
END;