DECLARE
  V_E_NAME EMPLOYEES.LAST_NAME%TYPE; 
  V_EMP_SAL EMPLOYEES.SALARY%TYPE:=2000;
BEGIN
  SELECT LAST_NAME INTO V_E_NAME
  FROM EMPLOYEES
  WHERE SALARY = V_EMP_SAL;
    --DBMS_OUTPUT.PUT_LINE('APELL IDOS: '||V_E_NAME);
    INSERT INTO MESSAGES (RESULTS) VALUES(V_E_NAME||' - '||V_EMP_SAL);
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO MESSAGES (RESULTS) VALUES('NO SE ENCONTRARON REGISTROS PARA EL EMPLEADO '||TO_CHAR(V_EMP_SAL));
    --DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRARON REGISTROS PARA EL EMPLEADO '||TO_CHAR(V_EMP_SAL));
  WHEN TOO_MANY_ROWS THEN
    INSERT INTO MESSAGES (RESULTS) VALUES('SE ENCONTRARON MÁS DE UN REGISTRO PARA EL EMPLEADO '||TO_CHAR(V_EMP_SAL));
  WHEN OTHERS THEN
  INSERT INTO MESSAGES (RESULTS) VALUES('SE ENCONTRÓ OTRO TIPO DE NOVEDAD PARA EL EMPLEADO '||TO_CHAR(V_EMP_SAL));
    
   
  
END;