SELECT * FROM 
JOBS B RIGHT JOIN JOB_HISTORY C
ON B.JOB_ID = C.JOB_ID;

SELECT * FROM 
JOBS B LEFT JOIN JOB_HISTORY C
ON B.JOB_ID = C.JOB_ID
AND C.JOB_ID IS NULL;

SELECT * FROM 
JOBS B INNER JOIN JOB_HISTORY C
ON B.JOB_ID = C.JOB_ID
AND C.JOB_ID IS NULL;

SELECT * FROM 
JOBS B FULL OUTER JOIN JOB_HISTORY C
ON B.JOB_ID = C.JOB_ID
WHERE B.JOB_ID IS NULL
AND C.JOB_ID IS NULL;







