SET SERVEROUTPUT ON
DECLARE
  EDAD NUMBER:=17;
BEGIN
  IF EDAD < 18
    THEN
      DBMS_OUTPUT.PUT_LINE('ERES MENOR DE EDAD');
  ELSE
      DBMS_OUTPUT.PUT_LINE('ERES MAYOR DE EDAD');
  END IF;
END;