--CASE BÚSQUEDA

SET VERIFY OFF
DECLARE
  V_GRADE CHAR(1):= UPPER('&GRADO');
  V_APPRAISAL  VARCHAR2(20);  
BEGIN
  V_APPRAISAL := CASE
      WHEN V_GRADE = 'A' THEN 'EXCELENTE'
      WHEN V_GRADE IN ('B','C') THEN 'MUY BIEN'
      ELSE 'NO SE ENCUENTRA LA OPCIÓN'
      END;
  DBMS_OUTPUT.PUT_LINE('GRADE: '|| V_GRADE || ' EVALUACIÓN: '||V_APPRAISAL);
END;
/