SET VERIFY OFF
DECLARE
  V_GRADE CHAR(1):= UPPER('&GRADO');
  V_APPRAISAL  VARCHAR2(20);  
BEGIN
  V_APPRAISAL := CASE V_GRADE
      WHEN 'A' THEN 'EXCELENTE'
      WHEN 'B' THEN 'MUY BIEN'
      WHEN 'C' THEN 'BIEN'
      ELSE 'NO SE ENCUENTRA LA OPCIÓN'
      END;
  DBMS_OUTPUT.PUT_LINE('GRADE: '|| V_GRADE || ' EVALUACIÓN: '||V_APPRAISAL);
END;
/