--SELECT * FROM EMPLOYEES
DECLARE
  V_SALARIOS NUMBER(10,2);
  V_DEPARTAMENTO NUMBER(3):=90;
BEGIN
  SELECT SUM(SALARY) INTO V_SALARIOS FROM EMPLOYEES
  WHERE DEPARTMENT_ID = V_DEPARTAMENTO;
  DBMS_OUTPUT.PUT_LINE('LA SUMA DE LOS SALARIOS ES DE: '||V_SALARIOS);
END;

SELECT SUM(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = 90;
