set serveroutput on
DECLARE
  V_DEPTID NUMBER;
  V_DEPTNAME VARCHAR2(20);
  V_EMPS NUMBER;
  V_MNGID NUMBER:=1;
BEGIN
  CASE V_MNGID
    WHEN 1 THEN
      SELECT DEPARTMENT_ID, DEPARTMENT_NAME INTO V_DEPTID, V_DEPTNAME FROM DEPARTMENTS
      WHERE MANAGER_ID = 114;
      SELECT COUNT(*) INTO V_EMPS FROM EMPLOYEES
      WHERE DEPARTMENT_ID = V_DEPTID;
  END CASE;
DBMS_OUTPUT.PUT_LINE('ESTÁS TRABAJANDO EN EL '||V_DEPTNAME||' DEPARTAMENTO, AQUÍ HAY '||V_EMPS||' EMPLEADOS EN ESTE DEPARTAMENTO');
END;