SET SERVEROUTPUT ON
DECLARE
  V_ID EMPLOYEES.EMPLOYEE_ID%TYPE;
  V_NOMBRE VARCHAR2(30);
BEGIN
  SELECT EMPLOYEE_ID,FIRST_NAME INTO V_ID,V_NOMBRE
  FROM EMPLOYEES
  WHERE EMPLOYEE_ID = 201;
  DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL ID: '||V_ID||' ES: '||V_NOMBRE);
  DBMS_OUTPUT.PUT_LINE('LA LONGITUD DEL NOMBRE: '||V_NOMBRE||' ES DE '||LENGTH(V_NOMBRE)||' CARACTERES');
END;
