DECLARE
  TYPE LOCATION_TYPE IS TABLE OF LOCATIONS.CITY%TYPE;
  OFFICES LOCATION_TYPE;
  TABLE_COUNT NUMBER;
BEGIN
  OFFICES := LOCATION_TYPE('BOMBAY','TOKYO','SINGAPORE','OXFORD');
  FOR I IN 1..OFFICES.COUNT() LOOP
    DBMS_OUTPUT.PUT_LINE(OFFICES(I));
  END LOOP;
END;