SET SERVEROUTPUT ON
DECLARE
  V_MANAGER EMP.MANAGER_ID%TYPE:=100;  
  
BEGIN
  DELETE FROM EMP WHERE EMP.MANAGER_ID = V_MANAGER;
  IF SQL%FOUND THEN
    DBMS_OUTPUT.PUT_LINE('DATOS ENCONTRADOS Y ELIMINADOS');
    DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT||' REGISTROS ELIMINADOS');
  ELSE
    DBMS_OUTPUT.PUT_LINE('NO SE ENCUENTRAN EMPLEADOS');
  END IF;
END;