VARIABLE ENLACE NUMBER;
  SET AUTOPRINT ON
  DECLARE
    V_NUEVO NUMBER(6):=&EMPNO;
  BEGIN
  SELECT SALARY INTO :ENLACE FROM EMPLOYEES WHERE EMPLOYEE_ID = V_NUEVO;
END;
/
PRINT ENLACE
/*
SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE SALARY = :ENLACE;
*/
