SET SERVEROUTPUT ON
DECLARE

V_FNAME VARCHAR2(20);
BEGIN
  SELECT FIRST_NAME INTO V_FNAME FROM EMPLOYEES
  WHERE EMPLOYEE_ID = 100;
  DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL EMPLEADO ES: '||V_FNAME);
END;