SELECT * FROM STUDENTS;

SELECT FIRST_NAME, LAST_NAME, MAJOR FROM STUDENTS WHERE MAJOR ='History' or MAJOR ='Nutrition';

--CONCATENAR

SELECT FIRST_NAME ||' '|| LAST_NAME as NOMBRE_COMPLETO, MAJOR 
  FROM STUDENTS 
  WHERE MAJOR ='History' or MAJOR ='Nutrition';

--CONTAR

SELECT COUNT(ID) FROM STUDENTS;

SELECT COUNT(ID), MAJOR FROM STUDENTS
GROUP BY (MAJOR)
ORDER BY 1 ASC;

--PROMEDIO
SELECT AVG(CURRENT_CREDITS) FROM STUDENTS;

--MÁXIMO
SELECT MAX(CURRENT_CREDITS) FROM STUDENTS;

--MÍNIMO
SELECT MIN(CURRENT_CREDITS) FROM STUDENTS;

--SUBCONSULTA
SELECT * FROM STUDENTS
WHERE CURRENT_CREDITS = (SELECT MAX(CURRENT_CREDITS)FROM STUDENTS)
ORDER BY CURRENT_CREDITS DESC;

--FUNCTION LIKE
SELECT * FROM STUDENTS WHERE FIRST_NAME LIKE '%David%'

--FUNCTION NULL
SELECT NVL(:P, 45)FROM DUAL;

SELECT DECODE(:P1, 'MX','MÉXICO', 'LAS DEMÁS') from dual;

--JOIN
SELECT S.FIRST_NAME, S.LAST_NAME, RG.GRADE FROM STUDENTS S, REGISTERED_STUDENTS RG WHERE S.ID = RG.STUDENT_ID
SELECT * FROM REGISTERED_STUDENTS;